#!/usr/bin/env python3
"""
embed_fonts.py: inline a folder of .woff2 fonts into a TypeScript module as data URLs.

Remotion shots that load fonts over the local asset server can stall under a parallel render
(delayRender times out). Inlining makes font loading instant and offline.

Usage (repo root):
  python tools/embed_fonts.py <fonts-dir> <out.ts>

Each file becomes `export const <NAME> = 'data:font/woff2;base64,...'`, where NAME is the file
stem upper-cased with non-alphanumerics as underscores (Rubik-var.woff2 -> RUBIK_VAR).
"""
import base64
import re
import sys
from pathlib import Path


def main():
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    src, out = Path(sys.argv[1]), Path(sys.argv[2])
    lines = [f"// GENERATED by tools/embed_fonts.py from {src.as_posix()} (check each font's license).", ""]
    for f in sorted(src.glob("*.woff2")):
        name = re.sub(r"[^A-Z0-9]", "_", f.stem.upper())
        lines.append(f"export const {name} = 'data:font/woff2;base64,{base64.b64encode(f.read_bytes()).decode()}';")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{out}: {len(lines) - 2} fonts")


if __name__ == "__main__":
    main()
